<a href="https://colab.research.google.com/github/Hion-cy/ClassFiles/blob/main/Practica_4__AL263158_AL263158.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practica 4

* Matricula AL263158
* Programación para analítica descriptiva y predictiva


In [2]:
import numpy as np

Manipulación de matrices

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

Suma ambas matrices.
Resta la segunda matriz de la primera.
Multiplica la primera matriz por 2.
Realiza una multiplicación matricial entre las dos matrices.

In [7]:
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))
print(f'Matriz A:\n{A}')
print(f'Matriz B:\n{B}')

Matriz A:
[[2 3 4]
 [9 8 7]
 [2 5 9]]
Matriz B:
[[1 6 4]
 [2 8 6]
 [5 4 3]]


In [8]:
rsuma=A+B
print(f'Suma de matrices:\n{rsuma}')

Suma de matrices:
[[ 3  9  8]
 [11 16 13]
 [ 7  9 12]]


In [9]:
rresta=A-B
print(f'Resta de matrices:\n{rresta}')

Resta de matrices:
[[ 1 -3  0]
 [ 7  0  1]
 [-3  1  6]]


In [10]:
ma2= A * 2
print(f'Multiplicación de matriz A por 2:\n{ma2}')

Multiplicación de matriz A por 2:
[[ 4  6  8]
 [18 16 14]
 [ 4 10 18]]


In [11]:
C = np.dot(A, B)
print(f'Multiplicación de matrices A y B:\n{C}')

Multiplicación de matrices A y B:
[[ 28  52  38]
 [ 60 146 105]
 [ 57  88  65]]
